SELECT G.FISH_COUNT, FNI.FISH_NAME
FROM (SELECT FI.FISH_TYPE, COUNT(*) AS FISH_COUNT
        FROM FISH_INFO FI
        GROUP BY FI.FISH_TYPE) G
LEFT JOIN FISH_NAME_INFO FNI
ON G.FISH_TYPE = FNI.FISH_TYPE
ORDER BY G.FISH_COUNT DESC;
