-- 코드를 입력하세요
SELECT DISTINCT(car.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR car, CAR_RENTAL_COMPANY_RENTAL_HISTORY history
WHERE car.CAR_ID = history.CAR_ID
AND car.CAR_TYPE = "세단"
AND MONTH(history.START_DATE) = 10
ORDER BY car.CAR_ID desc;